PLATFORM-7895 | Update TippingOver to work with MW 1.39
Wikia/TippingOver pull request #10
Opened 2023-03-10 13:09 UTC by MrVanosh

## Links
* https://fandom.atlassian.net/browse/PLATFORM-7895
* https://github.com/Wikia/unified-platform/pull/13260

## Description

## Acceptance Criteria
- [ ] test for new code.

## Who might be interested

2023-03-10 13:25 UTC, maaartyyynaa approved these changes

2023-03-10 13:40 UTC, wera-trollcode approved these changes

2023-03-10 14:02 UTC, mszabo-wikia requested changes
The extension is referencing $wgParser which was removed. It causes an error on every pageview and should be fixed.

2023-03-10 14:39 UTC, mszabo-wikia requested changes

2023-03-10 14:39 UTC, mszabo-wikia commented on includes/WikiTooltips.php
> +		self::$mParser = MediaWikiServices::getInstance()->getParser();
The original code clones `wgParser`, so we may instead want to use `getParserFactory()->create()`.

2023-03-13 11:30 UTC, mszabo-wikia approved these changes

2023-05-31 12:02 UTC, merged